### ISSUE TITLE
Understanding plugins, notification system

### ISSUE THREAD

**Issue by adrianmihalko** [juggie/AlarmServer#64]
I want to understand plugins to write my own for Domoticz. So I am trying to configure notification in alarmserver:

1,ifttt:

[ifttt_maker]
enable=True
key=xyxyxyxyxyxyxyxyxyxyx
eventName=alarmserver

Log:
```
Apr 25 22:24:19 - DEBUG - core/envisalink.py:handle_line@134: RX < 610 - Zone Emelet Restored
Apr 25 22:24:19 - ERROR: Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home//domoticz/userscripts/AlarmServer/plugins/ifttt_maker.py", line 29, in iftttMakerRequest
    if iftttMakerRequestType == 'notify':
NameError: global name 'iftttMakerRequestType' is not defined
Apr 25 22:24:20 - ERROR: Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home//domoticz/userscripts/AlarmServer/plugins/pushover.py", line 29, in sendNotification
    res = yield http_client.fetch("https://api.pushover.net/1/messages.json", method='POST', headers={"Content-type": "application/x-www-form-urlencoded"}, body=body)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 400: Bad Request
```

2, Similar for pushover:

[pushover]
enable=True
usertoken=xyxyxyxyxyxyxxy

```
Apr 25 22:10:41 - ERROR: Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home//domoticz/userscripts/AlarmServer/plugins/pushover.py", line 29, in sendNotification
    res = yield http_client.fetch("https://api.pushover.net/1/messages.json", method='POST', headers={"Content-type": "application/x-www-form-urlencoded"}, body=body)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 400: Bad Request
```

My first question: what I am doing wrong? And I would like to know: in default setup Alarmserver is sending notification about all events (zone open/closed, armed, disarmed, etc...)?

**Comment by juggie** [comment]
You resolved this issue?
